---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth
  namespace: aintcode
spec:
  encryptedData:
    .dockerconfigjson: AgBFpqnZv+JyThhTfNQL4jCsWv8fD2h8DJFZ8EX/eULtJY+17QIdHhBPXyqG63yEKmltChphjuKcy9xVJWV3RoXhGsDYp5GF9zgNAVoJVdDk7NMcyfaf4RYauMH+IEzdYscSwnDudcGLi5GLD4MEwcYNFsXuwODDkXWo/zjNA2PSVgT+bXsk8TQmtcXddkymaoCbNTleUnwdBCCM4xDFL14opzFBfCTxtcJp+4KAaGVHo1Krff4Pm4pNw+Lu1lFbteCrJGQXTB3f/JUrL7RdF2r+nTr8TMDXaXoZi70pKWJHXeX2lTvUHHjlOzNZaFX4sDFhH/a3Cylon6u1cLbpTL+SXQZbAmtAn1AkTNNHcN4U9JpAFA+sEaoG2pEX1r1fTFZ5vSOI0T9Vuf0Dhgvh9OdY36l4jeNC7ZDPd8VfbJAw/xQ1DHOL6sc0TDb/O7LzxQBEPxGXClvb1oMy4QVHlEX9UYApJGPm1sHGNErFv2l2eegHwHWvg8O/tSXVisHShl6yvxXHSk6QJdj7s3ZNnE3GPjS5A2rQFep1XYNwSvA+THP1kQ9KG0g3ATF5+z9h+dfomK7KekKbfq7VU6Y1/vTlQfh8QmlQug+vI0lvme0rpN/hUaea1i4VijAxxp7Yr6asftavwZltRGZLcK9aJI6CI4vC3txGvKbaCeCd05j6c/BBRYeaFikq3omGb2ACuxX5o5T9hB82/0A10RHf2wgL2a+zHOpiiH4USh6VeSdDXq24JtsCHIrO25t3gh9BpxLnR6v8WMubWNGMWrXctwZUhPN4dj7MBi5r+9EIVxEJMmdfzzvNeNmorRDN0jBFp4Gi7JBq7RvIDikyZlFAqXC+MDmZtdH0krEMqpCQaGm9Pvb8NQqFePJU+W7J7TXhaaYKgdssmUI/c72nu8bjpbO6qnQuaPPWdAdWqiY=
  template:
    metadata:
      name: ghcr-auth
      namespace: aintcode
    type: kubernetes.io/dockerconfigjson
