---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: aintcode
spec:
  encryptedData:
    password: AgCd/FRl4cikWYF8H9SsBZdbWnHrMDH4f6kDl403mCWlcts+pPfVaLMeQ9MIjQasxJ/b4BNWOIEvyUAkqq4Auit0Vklps4t0TVWGM9HcANbou3xWu3tYEGJAhB8NNwA1kAt7X56R5XAlWQy2jn/Mff2A0KSXRBpUQE5DXpNGOQbyzsZnCvQypcEhOHcHZBsv+u9znHmyIbGLhyPpOsR/hbU9BKCJeklvTofVcczZhzjoUdF3+hhtms6d5W8W6sfEkNQFy419OTeXU1eddVlfm3nT7E3MTrSeDlH5jbiDn+JQonJCNgEXjQzx3KZ++ji8Kj+8x5sbD0N2b6rQ7kf04L1SzFJvvR9Y92EF9jALI0lKCBT3OrPANxC3lSIcQ/mAJyRMfFZXz+xK5P3zOBGjKxpn14tmdUd1kSyFlwxmXrPeCDSCUhy6Eq/dGUoFpeNgQpC0WFJrRDoXvddGQCO6kub2oknPe150oxWtNmlclJGQxLMG0yHcSI0o613uGeaiE/ylv8CZbQiyUjj/3EYWmSGuXSIL1IBGS7Zk+F9IHrfjeIHJP7UvF0CJJFts/IQMu3nNhSFY/EQSnH1DqnuKIhhLp2GfH4l+j3h1YE7sbG5uaE47lGXzdKhfgi/7MGJiTmHTAcoHC+YKIOytBY29ZlAA+KrGT5BP7WDR4u2f0s7T4oomFSqLlj4/2BWdG8e9PK/xaqCvnl+WWRFb3viRDsDtW1IOXKhcnYi65H5gyeoPyPaYQdkxn286LFxe4A==
    username: AgBjp8672ejhEJjnDgLGG0TNgiM79LZF/DSG7a0f3jBS6FxosOvxa1hHnlJNO4LydDdozxbldlYa3Ru2yBrV+Y7pyYlddn7pne8NHOkQX/vP2mRgwUfBpGLNV+VbtoLuWT9wxl9wxGSVfCGWF6CQsY6BIJUfGL9oJxGHV5huhyFNh5pHEBp2M8hG6YYxXttwGHcm2UzPbqa0RvOHfVaR9hZa2cvkakiliDiMS8w46ttXvh1KmX0pqcvbg+MhrvMutRfLPrNCEXC0w/a8oMbCxNgWyn+d2/vq7ODzoC8Orv4LzEVIxSeFOwxopojSV616Xv/OCzGHmjVPlGBD7LzfTbNcWRNZ+/doHNF/koUZs3rv1QSNSf8pYa1bU+u+OuGk2oDu21zA/AZqoelvg3x/od9Kd0oUI2Sd7KEw4/PBgvOZJ0v6ESfCH+FZBLK0Hx63eTi++jgqKIPLFsnXyqTNRQpylXj9+TQ6c63kdEugCBMLG3t930sPus5XY+Xieda+TsHpg5S5D7FoolMXZkVOlD/3p20Gb7cverxTlyskBQ2kmecSlqRor0RGuCw+OGfhaAflQIL6se/wk6WNpDA3/lUBs4gmc5JWaheWyWfAf1q8yEnU5z2OZwEmXhsVro0qLxh17SrGWu8ONSubh1TBmDV/xB8n43ZmSei8rs9I9pNq9kPQUTOvmWIJGv8RJKTBMoiMidVMOhfczQ==
  template:
    metadata:
      name: postgres-secret
      namespace: aintcode
    type: kubernetes.io/basic-auth
