---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: aintcode
spec:
  encryptedData:
    password: AgBYZ6VDQuGa2HAt++Sv/P0dEFFHosvtaHjWHk+upfR6CE9nR4pPFhc9pM/RGzKIjJw+qdu0l2HK6zJTFqvJlW1w02EgO/RK1tDFZr9cteSY+w/hsa9/cStVFO7stndLvD85WGFUeLvpdJHBVeWEBNvjFjWZpIZFqklmj9KAZC8VDo9C5nlB6j8rVp+OTLjY2mBVUQpjXn1Nr4OZ+fKon0uy3NMOG6znu1rDkxH9R/L05VJ3EgLvcy/mCjTg0lYnvd9wUdcUSPYvUyVDNbCqKmWvN8u4HW5/cJVZlJvF+Qjj+Fttt6ZSBP8a+6JCvq97QQBC/wd+mfqceJ0oP1M5yjidOR5hSU5I/mqz/hSFdardaSxBRp5yrI5Ov+Ok/E/PEH65noq5hMrz/oYOYUiHE4VZfX0j1h6cLLuAcf8jRVE+Ev1woixoRHxBc7pP4Rt4dj/ulBEq+kZKi47vV5yQJ5Yg1mEM6VgYl8B60aYgIGNYpmekNop6BiRNx776QZB9d6kzDijvJ4fxzQUrdWSwOMi23wgUYSCphrvPc3HfnDGS21dxdWuJGkdRo+aTWBT4lC5nBDTWtGvh5b2S/stM/aNLu9kgCJ0hA89CeozJSs4lwaCMlBOHgDMgCX2kuSm+MiYHtFzqqbnP46HxELq6XYNRXORGDvJWvqEEL8eWef4hG4pIScfYtbIQm5+REnCFWIDDs9KilUJWglWMLMaHIyfKjNPjcWVz9XyminIUwL+H3BmW6Gnukgrrxt/Opg==
    username: AgAhscsHhkMF6xt3mf+hpPQvX+NJDeJEcBsBUD9ZmOpgVOKAmd9v0IkIjjKCAQewukGwPr2mHkFKeXCoac78GOaol2wnu9yW7+I35awD3vOfMy1ltL7U2KOnTs4fqmVJcNy6j2EsM6y7FNJ2I/PDmF/lAqDYdtjafOXNPlWtHVgRC5BGo8HSJNoHFEOIIKTEhmkXl7rIpEAyvFzTjaFbZJph34mcMrRoj2FjLfGD0czIIaIfdJVNEOSAv8CYzRz857QHqwP7ozHaRSuiPvIBFWlGEpLd5lrkmrEOZzERyK0LiqCvvEvUx9qqCZGLXHf5DiNCa7CZH+dkzuz/omT/mYkNH8rWATau/aB+RjYQjiep26ulotzT36oA5emBPKnHYTP/sN7SIeP4N98+Qvzkb0raMEVo8kSs+3GPnJByIlHDNI4nZt+c7YUB1xRqCO1WHoXDuDCfBr/E3YXdv0mEd2AythjMOZJK5ppfl2UdFD4dYGhPyqjuBAtCYhQQKawrb8fRzRapd3TfpH7YC18h1bnItmMwkFJyST3F6lmPwkQyxiHSEGJsHC2iynRQJBG5aZxDSTeUxMqRGaPpVZi/jCE7NyLNWx/pOjNw7ivPE6szHuum6dIpj1pkDWWu0KvIXW20Hyv5goq33CYGmFCAVyFebG+epLdPawmr1eYHKhrsun7ol7IHfrnh3gzc+sLproSHfpJmH89f/A==
  template:
    metadata:
      name: postgres-secret
      namespace: aintcode
    type: kubernetes.io/basic-auth
