---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: aintcode
spec:
  encryptedData:
    password: AgB0FKMpkq9Ye1a7P5HdQ1fmteH9xrAKEUSWr2d21ZL8bB+QWH/zNoR9tce4uwXAPNtLtd9nT1RlOU8Rjb0G7bUcukjCfJ+GeKPTxjIV8VlaPF+K4205xm6gBphVw3+f1Y5PokzjAHqpEjC1mTHyEiC+MyMJ6aiib6sYVxoSWvIRNyhDbrv5h8tfGvpYomtO8IznzKSX6h2IP4cYyIO3fHjfPW4BVcSY12B0Jj6CGvgL5cY1qA2+q93SjYRmQ9eL8AP5qHNBXTR7qEgfrohCpJhd/dVmOuWxNkoZnBOyWtQedla0bq5FXsCsiVk6MrjiqMS6mxhDQ/3aDqSaK8FtxkUgQsAXeIXgY9QZJ4S5XM5COXFo8KvuVcAoFyUvgL3CiC3B29dyvFia5H1ex7jqNKSJ6S6qfvbcdyFzSm+XMop8Ucih6Q49b8SJrTwu5rErL9jdxLLMxGBwWcABMWgXFriYdEYPrw9FSoK/Tphn4rIhJDONPJ4J5JUAScLqXERBaTmqTH2Tzwo6E3a/39atIALNnxv9jIe1jK7d9fMpQWjeFLsRc1fNsXY2npSzsWN/JqhDK4sh1LUEExSdqTA70AY/mm2LdH+IpXMSwpbyxJY5rhVT9y1wazYeI8IWbBLbE5GIxaDgrFQkrcU7rddjWVHk2L55YI+kHA0HMW6VDhlrxKAgm8hkMGMX6D9BTn8GmROlxYYT7leB9A2fZbcnPGY+VUQPi5NCAFqfbY9SrcGW3MzivQ2GE/7Nv9AMotvtCUCSbNDjX2mhnQC6VIKeoNlO
    username: AgAQH6VVo/9DnNAw+uRfrrDqz+uYazOB5rfcpTa5HPHBKv6RGuee+JAg76u/+BB1GrdnbT/6YK7wcB4En/COJSoMfHdqJ+ynfyUHvcgL47uZrgS7xSBF1oHQNtNYBDooclxer4Er46LY2NsTODz5egZ/JoaMWj0ERZkb+FoZJo4tKl6uykxgknN/inphZfWws3KUyXHI+1r8XkKjylVlWpU7mPMBPJzdQMs0JQqitdlHmEPgfP7HhQPU8AlXk8bpjfdEGUFSZOq0BoCyhbxx7L2gvwfY1H3lafbfq6NDMENIi/Bk++K1faQW0qB5sk7Q/BaBJI9+hxsI6TCy/8ifyGegsg9boaXSoI1BxVb2NjTWw/3VPEzm0hKEAgeYwrjkUceq5viAPUPOgy7hb4HvJ7T/H6o6kZ6DTHKPO3YyWeaPfdgi19UJH6YrugsW4Pq3o8PDYv8gzTrc1EetwEC+LnN+SOxM5qLM96nJbcu8K1hbAiunlHF6uCkn6z2f99vUblCi8uzSENCcLpniz0laL2r5ZUomeNToJbwkyOw6IICkhktqxGdwkBK1W2zKZOoWdihP9MKvWcLL7TVBrY/yb3iNC4DmZ2MsscOmlWN15YvByL4Z4l5ED/pNyHmbGFrupceiPcx2mf3sYH1vHrPFvj4LFwto3smUiI4P9q8zeLWfVDp93i18SWLZAhJn+G90LIqWHNxv8a0YNA==
  template:
    metadata:
      name: postgres-secret
      namespace: aintcode
    type: kubernetes.io/basic-auth
