---
apiVersion: operator.victoriametrics.com/v1
kind: VMServiceScrape
metadata:
  name: flux
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  endpoints:
    - port: http-prom
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: flux-system
