---
apiVersion: operator.victoriametrics.com/v1
kind: VMServiceScrape
metadata:
  name: traefik
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
